Suggestion: --quiet instead of > /dev/null
helen/action-wordpress-plugin-deploy pull request #39
Opened 2020-05-13 20:25 UTC by nextgenthemes

* I think the commands will output serious errors with `--quiet` and not just suppress everything. SVN says it displays nothing or just a summary so it's probably a good fit here. I prefer it in general for all commands that have it from what I learned.
* Redirecting to /dev/null means the output is still written and then discarded, that's less efficient than not writing it (and not allocate, prepare that output to be written)

[Source for 2nd point and more info on this](https://unix.stackexchange.com/questions/191254/why-do-many-commands-provide-a-quiet-option)

2020-05-14 02:26 UTC, helen commented
This seems fine to me - I'd love to know what SVN could potentially show for the `add` and `rm` commands just for due diligence, it's possible it would actually show more useful info if it's a reasonable summary.

2022-11-15 15:20 UTC, faisal-alvi requested changes
@jeffpaul the changed file `entrypoint.sh` is renamed in https://github.com/10up/action-wordpress-plugin-deploy/commit/8926c88630933b95c9ddf9279f95dc9176447eae to `deploy.sh` and there are lots of changes made in that file since this PR was raised leaving conflicts behind that can not be resolved from the browser, only @nextgenthemes can resolve the conflicts as the PR was raised from the forked repository. After the conflicts are resolved, we will be good to merge this PR. OR we can create a fresh PR with the props given to the @nextgenthemes.

2023-01-09 17:10 UTC, jeffpaul commented
@nextgenthemes are you able to help resolve the merge conflicts that Faisal noted above?

2023-01-09 17:41 UTC, nextgenthemes commented
Not really, I am not really up for spending any time on this.  It was just a TINY suggestion that does not really mater that much. I am running my own action based on this written on php if anyone is interested. https://github.com/nextgenthemes/advanced-responsive-video-embedder/blob/master/actions/wp-plugin-deploy/wp-plugin-deploy.php

It works locally and on Github with the same script. It also supports what I called "workingdir" that enabled it to operate out of a different folder or something like was mission on this.

Feel free to edit this --quiet in yourself for this.

2023-01-09 22:20 UTC, jeffpaul commented
@nextgenthemes thanks for the quick response, understood and I appreciate the contribution either way!

@10up/open-source-practice if anyone is interested in picking this up, then please go for it, otherwise if this sits without updates I'll likely close at some point 🙏🏼

2023-04-11 21:11 UTC, closed without merging